/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package linkup.presentacion.cu.gestionarInvitacion;

import linkup.objetosnegocio.cu.admInvitacion.Invitacion;
import linkup.presentacion.control.ControlAdministrarInvitaciones;

/**
 *
 * @author santi
 */
public class panelInvitacion extends javax.swing.JPanel {

    /**
     * Creates new form panelInvitacion
     */
    private Invitacion invitacion;
    private ControlAdministrarInvitaciones controlai;
    
    public panelInvitacion(Invitacion invitacion, ControlAdministrarInvitaciones controlai) {
        this.invitacion = invitacion;
        initComponents();
        RellenarInvitacion();
    }
    
    public void RellenarInvitacion(){
        NombreEventoLabel.setText(invitacion.getEvento().getNombreEvento());
        etiDescripcion.setText(invitacion.getEvento().getDescripcion());
        etiLugar.setText(invitacion.getEvento().getDireccion());
        etiFecha.setText(invitacion.getEvento().getFechaHora().toString());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreEventoLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnAceptar = new javax.swing.JButton();
        BtnRechazar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        etiLugar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etiDescripcion = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        etiFecha = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        NombreEventoLabel.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        NombreEventoLabel.setForeground(new java.awt.Color(168, 91, 102));
        NombreEventoLabel.setText("NombreEvento");
        NombreEventoLabel.setAlignmentX(0.5F);
        NombreEventoLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 1));
        add(NombreEventoLabel, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(542, 75));

        BtnAceptar.setBackground(new java.awt.Color(246, 227, 230));
        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Aceptar.png"))); // NOI18N
        BtnAceptar.setBorder(null);
        BtnAceptar.setContentAreaFilled(false);
        BtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        BtnRechazar.setBackground(new java.awt.Color(246, 227, 230));
        BtnRechazar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rechazar.png"))); // NOI18N
        BtnRechazar.setBorder(null);
        BtnRechazar.setContentAreaFilled(false);
        BtnRechazar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRechazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(BtnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnRechazar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiLugar.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        etiLugar.setForeground(new java.awt.Color(0, 0, 0));
        etiLugar.setText("Lugar");
        etiLugar.setAlignmentX(0.5F);
        etiLugar.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 1));
        jPanel2.add(etiLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 370, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 153));
        jLabel7.setText("Descrpcion");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 1));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("Lugar evento:");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 1));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));

        etiDescripcion.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        etiDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        etiDescripcion.setText("Descripcion");
        etiDescripcion.setAlignmentX(0.5F);
        etiDescripcion.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 1));
        jPanel2.add(etiDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 480, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 153));
        jLabel10.setText("Fecha evento:");
        jLabel10.setAlignmentX(0.5F);
        jLabel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        etiFecha.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        etiFecha.setForeground(new java.awt.Color(0, 0, 0));
        etiFecha.setText("Fecha");
        etiFecha.setAlignmentX(0.5F);
        etiFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 20, 5, 1));
        jPanel2.add(etiFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 360, -1));

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        controlai.aceptarInvitacion(invitacion.getEvento());
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRechazarActionPerformed
        // TODO add your handling code here:
        controlai.rechazar(invitacion.getEvento());
    }//GEN-LAST:event_BtnRechazarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnRechazar;
    private javax.swing.JLabel NombreEventoLabel;
    private javax.swing.JLabel etiDescripcion;
    private javax.swing.JLabel etiFecha;
    private javax.swing.JLabel etiLugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
