/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linkup.presentacion;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JTextField;
import linkup.dtosnegocios.EventoDTO;
import linkup.objetosnegocio.Etiqueta;
import linkup.presentacion.control.ControlCrearEvento;

/**
 *
 * @author leoca
 */
public class AdministrarEvento extends javax.swing.JFrame {

    private EventoDTO eventoDTO;
    private ControlCrearEvento controlEvento;
    List<EventoDTO> eventos;

    /**
     * Creates new form ActualizarEvento
     */
    public AdministrarEvento() {
        initComponents();
    }

    public AdministrarEvento(EventoDTO eventoDTO, ControlCrearEvento controlEvento, List<EventoDTO> eventos) {
        this.eventoDTO = eventoDTO;
        this.controlEvento = controlEvento;
        this.eventos = eventos;
        initComponents();
        setLocationRelativeTo(null);

        JTextField[] campos = {
            jTextField1, jTextField2, jTextField3,
            jTextField4, jTextField5, jTextField6
        };

        for (JTextField campo : campos) {
            campo.setOpaque(false);
            campo.setBackground(new Color(0, 0, 0, 0));
            campo.setBorder(null);
            campo.setForeground(Color.BLACK);
            campo.setEditable(false);
        }

        jComboBoxEtiqueta.setSelectedItem(eventoDTO.getEtiqueta().getTexto());
        jComboBoxEtiqueta.setEnabled(false);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String fechaTexto = eventoDTO.getFechaHora().format(formatter);

        DateTimeFormatter formatter2 = DateTimeFormatter.ofPattern("HH:mm");
        String horaTexto = eventoDTO.getFechaHora().format(formatter2);

        jTextField4.setText(horaTexto);

        jTextField4.setText(fechaTexto);

        jTextField1.setText(eventoDTO.getNombreEvento());
        jTextField2.setText(eventoDTO.getEtiqueta().getTexto());
        jTextField3.setText(eventoDTO.getDescripcion());
        jTextField4.setText(fechaTexto);
        jTextField5.setText(horaTexto);
        jTextField6.setText(eventoDTO.getDireccion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    public Etiqueta obtenerEtiquetaSeleccionada() {
        String seleccion = (String) jComboBoxEtiqueta.getSelectedItem();
        return Etiqueta.valueOf(seleccion.toUpperCase());
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jComboBoxEtiqueta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 270, 30));

        jTextField2.setBorder(null);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 270, 40));

        jTextField3.setBorder(null);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 270, 30));

        jTextField4.setBorder(null);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 270, 30));

        jTextField5.setBorder(null);
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 270, 40));

        jTextField6.setBorder(null);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, 270, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonEditarDatosEvento.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 40, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonEditarDatosEvento.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 40, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonEditarDatosEvento.png"))); // NOI18N
        jButton3.setText("jButton1");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 40, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonEditarDatosEvento.png"))); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 40, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonEditarDatosEvento.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 40, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonEditarDatosEvento.png"))); // NOI18N
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, 30, 30));

        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonregresar.png"))); // NOI18N
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 650, 180, 70));

        jComboBoxEtiqueta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cumpleaños", "Boda", "Reunion" }));
        getContentPane().add(jComboBoxEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoAdministrarrEvento.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField1.setEditable(!jTextField1.isEditable());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jComboBoxEtiqueta.setEnabled(!jComboBoxEtiqueta.isEnabled());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField3.setEditable(!jTextField3.isEditable());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField4.setEditable(!jTextField4.isEditable());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField5.setEditable(!jTextField5.isEditable());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField6.setEditable(!jTextField6.isEditable());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        List<EventoDTO> listaEventos = eventos;

        for (EventoDTO e : listaEventos) {
            if (e.getIdExterno().equals(eventoDTO.getIdExterno())) {

                e.setNombreEvento(jTextField1.getText());
                e.setEtiqueta(obtenerEtiquetaSeleccionada());
                e.setDescripcion(jTextField3.getText());

                String fechaStr = jTextField4.getText();
                String horaStr = jTextField5.getText();

                LocalDateTime nuevaFechaHora = LocalDateTime.parse(fechaStr + "T" + horaStr);
                e.setFechaHora(nuevaFechaHora);

                e.setDireccion(jTextField6.getText());
                break;
            }
        }
        controlEvento.setEventos(listaEventos);
        controlEvento.mostrarVentanaPrincipal();
        dispose();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboBoxEtiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
