/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linkup.presentacion;

import ISubsistema.IGestorContactos;
import Subsistema.GestorContactos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import linkup.objetosnegocio.UsuarioON;
import linkup.presentacion.control.ControlAdministrarGrupo;
import linkup.presentacion.control.ControlCrearEvento;

/**
 *
 * @author Dana Chavez
 */
public class AgregarContactos extends javax.swing.JFrame {
    
    private IGestorContactos gestorContactos = new GestorContactos();
    private ControlCrearEvento control;

    public AgregarContactos(ControlCrearEvento control) {
        initComponents();
        this.control = control;
        
        setLocationRelativeTo(null);
    }

    private void agregarContacto() {
        String usernameNuevo = jTextFieldBuscador.getText().trim();
        String usernameActual = UsuarioON.getInstance().getUsername();

        if (usernameNuevo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un nombre de usuario.");
            return;
        }

        
            boolean existe;
        try {
            existe = gestorContactos.validarExistenciaUsername(usernameNuevo);
            
            if (!existe) {
                JOptionPane.showMessageDialog(this, "El usuario no existe o el username es inválido.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            } catch (exception.NegocioException ex) {
                Logger.getLogger(AgregarContactos.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error al validar el usuario. Inténtalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }


            gestorContactos.agregarContacto(usernameActual, usernameNuevo);
            
            JOptionPane.showMessageDialog(this, "Contacto agregado exitosamente.");
            jTextFieldBuscador.setText("");
    }
       
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMisEventos = new javax.swing.JButton();
        jButtonChat = new javax.swing.JButton();
        jButtonCalendario = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldBuscador = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonMisAmigos = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMisEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmiseventos.png"))); // NOI18N
        jButtonMisEventos.setBorder(null);
        jButtonMisEventos.setContentAreaFilled(false);
        jButtonMisEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMisEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisEventosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMisEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        jButtonChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonchat.png"))); // NOI18N
        jButtonChat.setBorder(null);
        jButtonChat.setContentAreaFilled(false);
        jButtonChat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChatActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, -1));

        jButtonCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoncalendario.png"))); // NOI18N
        jButtonCalendario.setBorder(null);
        jButtonCalendario.setContentAreaFilled(false);
        jButtonCalendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, -1));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmenu.png"))); // NOI18N
        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 100, 750));

        jPanel2.setBackground(new java.awt.Color(152, 78, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBuscador.setText("Username");
        jPanel2.add(jTextFieldBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 40));

        jButtonAgregar.setText("jButton1");
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 520, 360));

        jPanel3.setBackground(new java.awt.Color(248, 225, 228));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(168, 91, 102));
        jLabelTitulo.setText("Mis Amigos");
        jPanel3.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 20, 120, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 540, 420));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LINK UP.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, 50));

        jButtonMisAmigos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmisamigos.png"))); // NOI18N
        jButtonMisAmigos.setBorder(null);
        jButtonMisAmigos.setContentAreaFilled(false);
        jButtonMisAmigos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMisAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMisAmigosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMisAmigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 60, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondosimple.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 1160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        agregarContacto();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonMisEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisEventosActionPerformed
        cerrar();
        control.mostrarVentanaPrincipal();
    }//GEN-LAST:event_jButtonMisEventosActionPerformed

    private void jButtonMisAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMisAmigosActionPerformed
        control.mostrarAgregarContactos();
    }//GEN-LAST:event_jButtonMisAmigosActionPerformed

    private void jButtonChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChatActionPerformed
        ControlAdministrarGrupo.getInstancia().iniciarFlujoGrupos();
        cerrar();
    }//GEN-LAST:event_jButtonChatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCalendario;
    private javax.swing.JButton jButtonChat;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonMisAmigos;
    private javax.swing.JButton jButtonMisEventos;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldBuscador;
    // End of variables declaration//GEN-END:variables
}
