/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linkup.presentacion;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import linkup.dtosnegocios.EventoDTO;
import linkup.objetosnegocio.Etiqueta;
import linkup.organizadoreventos.interfaces.IOrganizadorEventos;
import linkup.presentacion.control.ControlCrearEvento;

/**
 *
 * @author Dana Chavez
 */
public class ConfirmacionEvento extends javax.swing.JFrame {

    private ControlCrearEvento controlador;
    private EventoDTO eventoDTO;
    private IOrganizadorEventos organizadorEventos;
    private List<EventoDTO> eventos;

    /**
     * Creates new form VentanaPrincipalCrearEvento
     */

//     
    public ConfirmacionEvento(ControlCrearEvento controlador, EventoDTO eventoDTO, IOrganizadorEventos organizadorEventos) {
        this.controlador = controlador;
        this.eventoDTO = eventoDTO;
        this.organizadorEventos = organizadorEventos;
        initComponents();
        mostrarDatosEvento();
        setLocationRelativeTo(null);
    }

    public ConfirmacionEvento() {
        initComponents();
    }

    public void mostrar() {
        setVisible(true);
    }

    public void cerrar() {
        setVisible(false);
        dispose();
    }

    public void mostrarDatosEvento() {
        String etiquetaString = "";
        if (eventoDTO.getEtiqueta() == Etiqueta.CUMPLEAÑOS) {
            etiquetaString = "Cumpleaños";
        } else if (eventoDTO.getEtiqueta() == Etiqueta.BODA) {
            etiquetaString = "Boda";
        } else if (eventoDTO.getEtiqueta() == Etiqueta.REUNION) {
            etiquetaString = "Reunion";
        }

        LocalDateTime fechaHora = eventoDTO.getFechaHora();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String fechaHoraFormateada = fechaHora.format(formatter);

        jTextFieldNombre.setText(eventoDTO.getNombreEvento());
        jTextFieldDescripcion.setText(eventoDTO.getDescripcion());
        jTextFieldEtiqueta.setText(etiquetaString);
        jTextFieldUbicacion.setText(eventoDTO.getDireccion());
        jTextFieldFechaHora.setText(fechaHoraFormateada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanelDetalles = new javax.swing.JPanel();
        jLabelNombreEvento = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelEtiqueta = new javax.swing.JLabel();
        jLabelUbicacion = new javax.swing.JLabel();
        jLabelFechaHora = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldEtiqueta = new javax.swing.JTextField();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jTextFieldFechaHora = new javax.swing.JTextField();
        jLabelDetallesEvento = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonMenu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonInicio1 = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        jLabelLogo1 = new javax.swing.JLabel();
        jButtonAnterior1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(168, 91, 102));
        jLabel7.setText("Banner");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonchat.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, -1));

        jPanelDetalles.setBackground(new java.awt.Color(152, 79, 89));
        jPanelDetalles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombreEvento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreEvento.setText("Nombre:");
        jPanelDetalles.add(jLabelNombreEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcion.setText("Descripcion:");
        jPanelDetalles.add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabelEtiqueta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEtiqueta.setText("Etiqueta:");
        jPanelDetalles.add(jLabelEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabelUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUbicacion.setText("Ubicación:");
        jPanelDetalles.add(jLabelUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabelFechaHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFechaHora.setText("Fecha Hora:");
        jPanelDetalles.add(jLabelFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jTextFieldNombre.setEditable(false);
        jPanelDetalles.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 150, -1));

        jTextFieldDescripcion.setEditable(false);
        jPanelDetalles.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 150, -1));

        jTextFieldEtiqueta.setEditable(false);
        jPanelDetalles.add(jTextFieldEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, -1));

        jTextFieldUbicacion.setEditable(false);
        jPanelDetalles.add(jTextFieldUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, -1));

        jTextFieldFechaHora.setEditable(false);
        jPanelDetalles.add(jTextFieldFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 150, -1));

        getContentPane().add(jPanelDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 270, 340));

        jLabelDetallesEvento.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelDetallesEvento.setForeground(new java.awt.Color(168, 91, 102));
        jLabelDetallesEvento.setText("Detalles del evento");
        getContentPane().add(jLabelDetallesEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 160, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonconfirmar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmiseventos.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lblcreandoevento.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 210, -1));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmenu.png"))); // NOI18N
        jButtonMenu.setContentAreaFilled(false);
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoncalendario.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, -1));

        jButtonInicio1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoninicio.png"))); // NOI18N
        jButtonInicio1.setBorder(null);
        jButtonInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicio1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 50));

        jButtonCancelar1.setBackground(new java.awt.Color(246, 227, 230));
        jButtonCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoncancelar.png"))); // NOI18N
        jButtonCancelar1.setContentAreaFilled(false);
        jButtonCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, -1, -1));

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LINK UP.png"))); // NOI18N
        getContentPane().add(jLabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, 50));

        jButtonAnterior1.setBackground(new java.awt.Color(246, 227, 230));
        jButtonAnterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonregresar.png"))); // NOI18N
        jButtonAnterior1.setContentAreaFilled(false);
        jButtonAnterior1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnterior1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevoevento.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 1200, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 100, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButtonInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInicio1ActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed

        controlador.mostrarVentanaPrincipal();
        cerrar();
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void jButtonAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnterior1ActionPerformed
        controlador.mostrarSeleccionarUbicacion(eventoDTO);
        cerrar();
    }//GEN-LAST:event_jButtonAnterior1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmacionEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAnterior1;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonInicio1;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDetallesEvento;
    private javax.swing.JLabel jLabelEtiqueta;
    private javax.swing.JLabel jLabelFechaHora;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel jLabelNombreEvento;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldEtiqueta;
    private javax.swing.JTextField jTextFieldFechaHora;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUbicacion;
    // End of variables declaration//GEN-END:variables
}
