/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linkup.presentacion;

import linkup.dtosnegocios.ContactoDTO;
import linkup.dtosnegocios.EventoDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import linkup.presentacion.control.ControlCrearEvento;

/**
 *
 * @author Dana Chavez
 */
public class EnviarInvitaciones extends javax.swing.JFrame {

    private ControlCrearEvento controlador;
    private List<JCheckBox> checkboxes;
    private EventoDTO eventoDTO;
    public List<ContactoDTO> seleccionados;
    /**
     * Creates new form VentanaPrincipalCrearEvento
     */
    
    
    public EnviarInvitaciones(ControlCrearEvento controlador, EventoDTO eventoDTO) {
        this.controlador = controlador;
        this.eventoDTO = eventoDTO;
        this.checkboxes = new ArrayList<>();
        this.seleccionados = new ArrayList<>(); 
        initComponents();
         mostrarContactos();
        setLocationRelativeTo(null);
    }
    
     public void mostrarContactos(){
        for (ContactoDTO ContactoDTO : controlador.ObtenerContactos()) {
                JCheckBox checkBox = new JCheckBox(ContactoDTO.getNombre());
                checkboxes.add(checkBox);
                contactosPanel.add(checkBox);
        }
    }
     
     private void generarListaSeleccionados() {

        for (int i = 0; i < checkboxes.size(); i++) {
        JCheckBox checkBox = checkboxes.get(i);
        if (checkBox.isSelected()) {
            seleccionados.add(controlador.ObtenerContactos().get(i));
        }
    }   
    }

    public EnviarInvitaciones() {
        initComponents();
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanelBlanco = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelInvitacionesYDetalles = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        contactosPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonCopiarEnlace = new javax.swing.JButton();
        jLabelEnviarNotificaciones = new javax.swing.JLabel();
        jLabelGenerarAlbum = new javax.swing.JLabel();
        jCheckBoxEnviarNotificaciones = new javax.swing.JCheckBox();
        jCheckBoxGenerarAlbum = new javax.swing.JCheckBox();
        jButtonInicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(168, 91, 102));
        jLabel7.setText("Banner");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancelar.setBackground(new java.awt.Color(246, 227, 230));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoncancelar.png"))); // NOI18N
        jButtonCancelar.setContentAreaFilled(false);
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelBlanco.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, -1, -1));

        jButtonAnterior.setBackground(new java.awt.Color(246, 227, 230));
        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonregresar.png"))); // NOI18N
        jButtonAnterior.setContentAreaFilled(false);
        jButtonAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        jPanelBlanco.add(jButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        jButtonSiguiente.setBackground(new java.awt.Color(246, 227, 230));
        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonsiguiente.png"))); // NOI18N
        jButtonSiguiente.setContentAreaFilled(false);
        jButtonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        jPanelBlanco.add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, -1, -1));

        jLabelInvitacionesYDetalles.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabelInvitacionesYDetalles.setForeground(new java.awt.Color(168, 91, 102));
        jLabelInvitacionesYDetalles.setText("Invitaciones y detalles");
        jPanelBlanco.add(jLabelInvitacionesYDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 190, -1));

        jPanel5.setBackground(new java.awt.Color(152, 79, 89));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(241, 212, 217));
        jTextField1.setForeground(new java.awt.Color(168, 91, 102));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 30));

        contactosPanel.setLayout(new javax.swing.BoxLayout(contactosPanel, javax.swing.BoxLayout.Y_AXIS));
        jPanel5.add(contactosPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, 170));

        jPanelBlanco.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 270, 230));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmiseventos.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jPanelBlanco.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonchat.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jPanelBlanco.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoncalendario.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jPanelBlanco.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, -1));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmenu.png"))); // NOI18N
        jButtonMenu.setContentAreaFilled(false);
        jPanelBlanco.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jButtonCopiarEnlace.setBackground(new java.awt.Color(246, 227, 230));
        jButtonCopiarEnlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/linkupbotonenlace.png"))); // NOI18N
        jPanelBlanco.add(jButtonCopiarEnlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 220, 50));

        jLabelEnviarNotificaciones.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabelEnviarNotificaciones.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEnviarNotificaciones.setText("Enviar notificaciones del evento");
        jPanelBlanco.add(jLabelEnviarNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 220, -1));

        jLabelGenerarAlbum.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabelGenerarAlbum.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGenerarAlbum.setText("Generar un album de recuerdos");
        jPanelBlanco.add(jLabelGenerarAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 220, -1));
        jPanelBlanco.add(jCheckBoxEnviarNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 30, -1));

        jCheckBoxGenerarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGenerarAlbumActionPerformed(evt);
            }
        });
        jPanelBlanco.add(jCheckBoxGenerarAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 30, -1));

        jButtonInicio.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoninicio.png"))); // NOI18N
        jButtonInicio.setBorder(null);
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        jPanelBlanco.add(jButtonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lblcreandoevento.png"))); // NOI18N
        jPanelBlanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 210, -1));

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LINK UP.png"))); // NOI18N
        jPanelBlanco.add(jLabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevoevento.png"))); // NOI18N
        jPanelBlanco.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 1200, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(168, 91, 102));
        jLabel4.setText("Seleccionar fecha y hora");
        jPanelBlanco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        getContentPane().add(jPanelBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxGenerarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGenerarAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxGenerarAlbumActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        controlador.mostrarVentanaPrincipal();
        cerrar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        controlador.mostrarSeleccionarUbicacion(eventoDTO);
        cerrar();
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        generarListaSeleccionados();
        eventoDTO.setInvitados(seleccionados);
        
        controlador.mostrarConfirmacionEvento(eventoDTO);
        cerrar();
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnviarInvitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnviarInvitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnviarInvitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnviarInvitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnviarInvitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contactosPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCopiarEnlace;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JCheckBox jCheckBoxEnviarNotificaciones;
    private javax.swing.JCheckBox jCheckBoxGenerarAlbum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelEnviarNotificaciones;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGenerarAlbum;
    private javax.swing.JLabel jLabelInvitacionesYDetalles;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBlanco;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
