/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linkup.presentacion;

import exception.NegocioException;
import javax.swing.JOptionPane;
import linkup.presentacion.control.ControlIniciarSesion;
import linkup.presentacion.control.ControlRegistrarUsuario;

/**
 *
 * @author gael_
 */
public class IniciarSesion extends javax.swing.JFrame {

    
    ControlIniciarSesion controlador;
    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion(ControlIniciarSesion controlador) {
        this.controlador=controlador;
        initComponents();
    }

    private void iniciarSesion() {
        try {
            String username = txtUsername.getText().trim();
            String contrasenia = txtConstraseña.getText().trim();

            if (username.isEmpty() || contrasenia.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, completa todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            boolean autenticado = controlador.iniciarSesion(username, contrasenia);

            if (autenticado) {
                JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso.", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
                //MODIFICAR CONSTRUCTOR DE CREAR EVENTOS PA QUE SIRVA
                //new VentanaPrincipalCrearEvento(controlador, eventos, controlador.getUsuarioActual());
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Nombre de usuario o contraseña incorrectos.", "Error de autenticación", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error de negocio", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error inesperado. Inténtalo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); // Opcional: para depuración
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBlanco = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtConstraseña = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        jLabelLogo1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1151, 744));

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));
        panelBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(168, 91, 102));
        labelUsuario.setText("Usuario:");
        panelBlanco.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 90, 30));

        labelContraseña.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        labelContraseña.setForeground(new java.awt.Color(168, 91, 102));
        labelContraseña.setText("Contraseña:");
        panelBlanco.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 110, 30));

        txtUsername.setBackground(new java.awt.Color(247, 165, 165));
        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        panelBlanco.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 220, 40));

        txtConstraseña.setBackground(new java.awt.Color(247, 165, 165));
        txtConstraseña.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtConstraseña.setForeground(new java.awt.Color(255, 255, 255));
        panelBlanco.add(txtConstraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 220, 40));

        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/linkupbotoniniciarsesion.png"))); // NOI18N
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        panelBlanco.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 220, -1));

        btnRegistrarse.setForeground(new java.awt.Color(168, 91, 102));
        btnRegistrarse.setText("No cuentas con una cuenta? Registrate");
        btnRegistrarse.setContentAreaFilled(false);
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        panelBlanco.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 260, -1));

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LINK UP.png"))); // NOI18N
        panelBlanco.add(jLabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 250, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondosimple.png"))); // NOI18N
        panelBlanco.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 1160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        ControlRegistrarUsuario control = new ControlRegistrarUsuario(this);
    }//GEN-LAST:event_btnRegistrarseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JTextField txtConstraseña;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
