/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linkup.presentacion;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import linkup.dtosnegocios.EventoDTO;
import linkup.presentacion.control.ControlAdministrarGrupo;
import linkup.presentacion.control.ControlCrearEvento;

/**
 *
 * @author Dana Chavez
 */
public class VentanaPrincipalCrearEvento extends javax.swing.JFrame {

    private ControlCrearEvento controlador;
    private List<EventoDTO> eventos;
    /**
     * Creates new form VentanaPrincipalCrearEvento
     */
    public VentanaPrincipalCrearEvento(ControlCrearEvento controlador, List<EventoDTO> eventos) {
        this.controlador = controlador;
        this.eventos  = eventos;
        initComponents();
        setLocationRelativeTo(null);
        cargarEventos();
    }

    public VentanaPrincipalCrearEvento() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void mostrar(){
        setVisible(true);
    }
    
    public void cerrar(){
        setVisible(false);
        dispose();
    }
    
    public void cargarEventos() {

    jPanelListaEventos.removeAll();
    jPanelListaEventos.setLayout(new BoxLayout(jPanelListaEventos, BoxLayout.Y_AXIS));
    jPanelListaEventos.setBackground(Color.WHITE);

    if (eventos != null && !eventos.isEmpty()) {
        for (EventoDTO evento : eventos) {
            EventoPanel panelEvento = new EventoPanel(evento);
            jPanelListaEventos.add(panelEvento);
            jPanelListaEventos.add(Box.createRigidArea(new Dimension(0, 10))); 
        }
    } else {
        JLabel labelVacio = new JLabel("No hay eventos disponibles.");
        labelVacio.setFont(new Font("SansSerif", Font.ITALIC, 14));
        labelVacio.setForeground(Color.GRAY);
        labelVacio.setAlignmentX(Component.CENTER_ALIGNMENT);
        jPanelListaEventos.add(labelVacio);
    }

    jPanelListaEventos.revalidate();
    jPanelListaEventos.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanelFondoBlanco = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButtonExplorar = new javax.swing.JButton();
        jButtonCrearEvento = new javax.swing.JButton();
        jScrollPaneListaEvento = new javax.swing.JScrollPane();
        jPanelListaEventos = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonInicio1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelFondo = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(168, 91, 102));
        jLabel4.setText("Seleccionar Ubicacion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(168, 91, 102));
        jLabel5.setText("Mis Eventos");
        jPanelFondoBlanco.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jButtonExplorar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonExplorar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonexplorar.png"))); // NOI18N
        jButtonExplorar.setBorder(null);
        jButtonExplorar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFondoBlanco.add(jButtonExplorar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 200, -1));

        jButtonCrearEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoncrearevento.png"))); // NOI18N
        jButtonCrearEvento.setBorder(null);
        jButtonCrearEvento.setContentAreaFilled(false);
        jButtonCrearEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearEventoActionPerformed(evt);
            }
        });
        jPanelFondoBlanco.add(jButtonCrearEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 190, 60));

        jScrollPaneListaEvento.setViewportView(jPanelListaEventos);

        jPanelFondoBlanco.add(jScrollPaneListaEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 380, 450));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LINK UP.png"))); // NOI18N
        jPanelFondoBlanco.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 250, 50));

        jButtonInicio1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInicio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoninicio.png"))); // NOI18N
        jButtonInicio1.setBorder(null);
        jButtonInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicio1ActionPerformed(evt);
            }
        });
        jPanelFondoBlanco.add(jButtonInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoncalendario.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFondoBlanco.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 60, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmiseventos.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanelFondoBlanco.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonchat.png"))); // NOI18N
        btnGrupos.setBorder(null);
        btnGrupos.setContentAreaFilled(false);
        btnGrupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });
        jPanelFondoBlanco.add(btnGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, -1));

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmenu.png"))); // NOI18N
        jButtonMenu.setBorder(null);
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFondoBlanco.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jPanel1.setBackground(new java.awt.Color(255, 248, 247));
        jPanelFondoBlanco.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 380, 490));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondosimple.png"))); // NOI18N
        jPanelFondoBlanco.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 1160, -1));

        getContentPane().add(jPanelFondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearEventoActionPerformed
        controlador.mostrarFormularioDetalles();
        cerrar();
    }//GEN-LAST:event_jButtonCrearEventoActionPerformed

    private void jButtonInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInicio1ActionPerformed

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        ControlAdministrarGrupo.getInstancia().iniciarFlujoGrupos();
        cerrar();
    }//GEN-LAST:event_btnGruposActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCrearEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalCrearEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCrearEvento;
    private javax.swing.JButton jButtonExplorar;
    private javax.swing.JButton jButtonInicio1;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFondoBlanco;
    private javax.swing.JPanel jPanelListaEventos;
    private javax.swing.JScrollPane jScrollPaneListaEvento;
    // End of variables declaration//GEN-END:variables
}
