/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linkup.presentacion.cu.admGrupo;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import linkup.objetosnegocio.cu.admgrupo.Grupo;
import linkup.presentacion.control.ControlAdministrarGrupo;
import linkup.presentacion.control.ControlCrearEvento;


/**
 *
 * @author gael_
 */
public class frmGruposPrincipal extends javax.swing.JFrame {
    
    public ControlAdministrarGrupo controlador;

    /**
     * Creates new form frmGruposPrincipal
     */
    public frmGruposPrincipal(ControlAdministrarGrupo controlador) {
        this.controlador = controlador;
        initComponents();
        setTitle("Grupos");
        setLocationRelativeTo(null);
        mostrarGrupos();
        tblGrupos.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent evt) {
            int filaSeleccionada = tblGrupos.getSelectedRow();
            if (filaSeleccionada >= 0) {
                String nombreGrupo = tblGrupos.getValueAt(filaSeleccionada, 0).toString();
                Grupo grupoSeleccionado = controlador.obtenerGrupoPorNombre(nombreGrupo);
                if (grupoSeleccionado != null) {
                    controlador.accederGrupo(grupoSeleccionado);
                    dispose(); 
                }
            }
        }
    });
    }
    
    public void mostrarGrupos(){
        List<Grupo> grupos = controlador.obtenerGrupos();
        
        String[] columnas = {"Grupos"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        };

        for (Grupo grupo : grupos) {
            String nombre = grupo.getNombre();
            modelo.addRow(new Object[]{nombre});
        }

        tblGrupos.setModel(modelo);
        
        Font fuenteGrande = new Font(tblGrupos.getFont().getName(), Font.PLAIN, 18); 
        tblGrupos.setFont(fuenteGrande);
        tblGrupos.getTableHeader().setFont(fuenteGrande); 

        tblGrupos.setRowHeight(50); 

        tblGrupos.setBackground(Color.WHITE); 
        tblGrupos.setForeground(new Color(102, 0, 102)); 

        JTableHeader header = tblGrupos.getTableHeader();
        header.setBackground(new Color(102, 0, 102));
        header.setForeground(Color.WHITE);

        scrollGrupos.setViewportView(tblGrupos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBlanco = new javax.swing.JPanel();
        PanelRosa = new javax.swing.JPanel();
        jButtonMenu = new javax.swing.JButton();
        btnCalendario = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();
        btnEventos = new javax.swing.JButton();
        PanelLogo = new javax.swing.JLabel();
        PanelMisGrupos = new javax.swing.JLabel();
        btnCrearGrupo = new javax.swing.JButton();
        scrollGrupos = new javax.swing.JScrollPane();
        tblGrupos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 750));
        setPreferredSize(new java.awt.Dimension(1160, 750));

        PanelBlanco.setBackground(new java.awt.Color(255, 255, 255));

        PanelRosa.setBackground(new java.awt.Color(253, 166, 179));
        PanelRosa.setMinimumSize(new java.awt.Dimension(56, 57));
        PanelRosa.setPreferredSize(new java.awt.Dimension(56, 57));
        PanelRosa.setLayout(null);

        jButtonMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmenu.png"))); // NOI18N
        jButtonMenu.setContentAreaFilled(false);
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        PanelRosa.add(jButtonMenu);
        jButtonMenu.setBounds(10, 20, 46, 47);

        btnCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoncalendario.png"))); // NOI18N
        btnCalendario.setContentAreaFilled(false);
        btnCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioActionPerformed(evt);
            }
        });
        PanelRosa.add(btnCalendario);
        btnCalendario.setBounds(10, 100, 46, 47);

        btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonchat.png"))); // NOI18N
        btnGrupos.setContentAreaFilled(false);
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });
        PanelRosa.add(btnGrupos);
        btnGrupos.setBounds(10, 160, 46, 47);

        btnEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonmiseventos.png"))); // NOI18N
        btnEventos.setContentAreaFilled(false);
        btnEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosActionPerformed(evt);
            }
        });
        PanelRosa.add(btnEventos);
        btnEventos.setBounds(10, 220, 46, 47);

        PanelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LINK UP.png"))); // NOI18N

        PanelMisGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMisGrupos.png"))); // NOI18N

        btnCrearGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCrearGrupo.png"))); // NOI18N
        btnCrearGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearGrupoActionPerformed(evt);
            }
        });

        scrollGrupos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(148, 63, 75)));

        tblGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollGrupos.setViewportView(tblGrupos);

        javax.swing.GroupLayout PanelBlancoLayout = new javax.swing.GroupLayout(PanelBlanco);
        PanelBlanco.setLayout(PanelBlancoLayout);
        PanelBlancoLayout.setHorizontalGroup(
            PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBlancoLayout.createSequentialGroup()
                .addComponent(PanelRosa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBlancoLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBlancoLayout.createSequentialGroup()
                                .addComponent(PanelMisGrupos)
                                .addGap(557, 557, 557)
                                .addComponent(btnCrearGrupo))
                            .addComponent(scrollGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelBlancoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PanelLogo)))
                .addContainerGap(857, Short.MAX_VALUE))
        );
        PanelBlancoLayout.setVerticalGroup(
            PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBlancoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PanelLogo)
                .addGap(33, 33, 33)
                .addGroup(PanelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelMisGrupos)
                    .addComponent(btnCrearGrupo))
                .addGap(30, 30, 30)
                .addComponent(scrollGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearGrupoActionPerformed
        controlador.crearGrupo();
        this.dispose();
    }//GEN-LAST:event_btnCrearGrupoActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void btnCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalendarioActionPerformed

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed

    }//GEN-LAST:event_btnGruposActionPerformed

    private void btnEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosActionPerformed
        ControlCrearEvento.getInstancia().iniciarFlujoCreacionEvento();
        this.dispose();
    }//GEN-LAST:event_btnEventosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBlanco;
    private javax.swing.JLabel PanelLogo;
    private javax.swing.JLabel PanelMisGrupos;
    private javax.swing.JPanel PanelRosa;
    private javax.swing.JButton btnCalendario;
    private javax.swing.JButton btnCrearGrupo;
    private javax.swing.JButton btnEventos;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JScrollPane scrollGrupos;
    private javax.swing.JTable tblGrupos;
    // End of variables declaration//GEN-END:variables
}
